global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
            
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: api-1
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - "api-1:5020"
        labels:
          app: "api-1"

  - job_name: api-2
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - "api-2:5020"
        labels:
          app: "api-2"
  
  - job_name: api-3
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets:
          - "api-3:5020"
        labels:
          app: "api-2"